#!/bin/sh

rm fort.*
rm ./ptrates


#gfortran -ffixed-line-length-none -o ptrates ptrates.f F1F209.f 
#gfortran -ffixed-line-length-none -o ptrates ptrates_b1.f F1F209.f sub_b1d.f sub_qe_b1d.f get_qe_b1.f inclusive.f
#gfortran -ffixed-line-length-none -o ptrates ptrates_b1_prop.f F1F209.f sub_b1d.f sub_qe_b1d.f get_qe_b1.f inclusive.f
gfortran -ffixed-line-length-none -o ptrates ptrates_b1_prop_hermes.f F1F209.f sub_b1d.f sub_qe_b1d.f get_qe_b1.f inclusive.f
#gfortran -ffixed-line-length-none -o ptrates ptrates_b1_t20.f F1F209.f sub_b1d.f sub_qe_b1d.f get_qe_b1.f inclusive.f
#gfortran -ffixed-line-length-none -o ptrates ptrates_b1_prop_update.f F1F209.f sub_b1d.f sub_qe_b1d.f get_qe_b1.f inclusive.f
#gfortran -ffixed-line-length-none -o ptrates ptrates_b1_20GeV.f F1F209.f sub_b1d.f sub_qe_b1d.f get_qe_b1.f inclusive.f
#gfortran -ffixed-line-length-none -o ptrates ptrates_b1_jeopardy.f F1F209.f sub_b1d.f sub_qe_b1d.f get_qe_b1.f inclusive.f

rm *.o
./ptrates
