#!/bin/sh

rm fort.*
rm ./ptrates

#gfortran -ffixed-line-length-none -o ptrates ptrates.f F1F209.f 
gfortran -ffixed-line-length-none -o ptrates ptrates_b1.f F1F209.f sub_b1d.f sub_qe_b1d.f


rm *.o
./ptrates
