#!/bin/sh

rm fort.*
rm ./ptrates

#gfortran -ffixed-line-length-none -o ptrates ptrates.f F1F209.f 
#gfortran -ffixed-line-length-none -o ptrates ptrates_azz.f F1F209.f sub_b1d.f sub_qe_b1d.f get_qe_b1.f
#gfortran -ffixed-line-length-none -o ptrates ptrates_azz_loi.f F1F209.f sub_b1d.f sub_qe_b1d.f get_qe_b1.f
#gfortran -ffixed-line-length-none -o ptrates ptrates_azz_prop2.f F1F209.f sub_b1d.f sub_qe_b1d.f get_qe_b1.f
#gfortran -ffree-line-length-0 -ffixed-line-length-0 -o ptrates ptrates_azz_prop.f F1F209.f sub_b1d.f sub_qe_b1d.f get_qe_b1.f inclusive.f elastic.f
#gfortran -ffree-line-length-0 -ffixed-line-length-0 -o ptrates ptrates_azz_prop2.f F1F209.f sub_b1d.f sub_qe_b1d.f get_qe_b1.f inclusive.f elastic.f
#gfortran -ffree-line-length-0 -ffixed-line-length-0 -o ptrates ptrates_azz_cscheck.f F1F209.f sub_b1d.f sub_qe_b1d.f get_qe_b1.f inclusive.f elastic.f
#gfortran -ffree-line-length-0 -ffixed-line-length-0 -o ptrates ptrates_azz_b1_t20.f F1F209.f sub_b1d.f sub_qe_b1d.f get_qe_b1.f inclusive.f elastic.f
gfortran -ffree-line-length-0 -ffixed-line-length-0 -o ptrates ptrates_azz_jeopardy.f F1F209.f sub_b1d.f sub_qe_b1d.f get_qe_b1.f inclusive.f elastic.f

rm *.o
./ptrates
